### ISSUE TITLE
该工具已经失效，可以github搜学无止下载器，可下载中国大学视频和课件资料

### ISSUE THREAD

**Issue by PyJun** [MoocDownloader/MoocDownloader#92]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Greenarrow1224** [comment]
别信他，这是个公司搞的收费软件

**Comment by zhangshuo98767** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
